### ISSUE TITLE
Agregar método parra extracción del tipo de sistema operativo

### ISSUE THREAD

**Issue by Bryan-Herrera-DEV** [Jeremymr2/joker-cibersecurity#1]
Buenas tardes, me gustaría programar un método que permita al script tener una función para extraer el tipo de sistema operativo sin el uso de nmap(es muy ruidoso).
Si me das el permiso lo hago, estaré atento a tu respuesta y en uno o dos días dependiendo mi tiempo libre hago el pull request.

**Comment by Jeremymr2** [comment]
Buenas tardes, Bryan.
Me parece interesante el aporte y tiene todo el permiso de implementarlo. Estaré atento a su pull request. Gracias!!

**Comment by Bryan-Herrera-DEV** [comment]
Ya esta hecho el pull request con los cambios pertinentes, espero sea de agrado para poder hacer el merge
